project:
  type: website

website:
  title: "گراف‌های یادگیری ماشین"
  description: "آموزش گراف‌های یادگیری ماشین - دانشگاه علامه طباطبائی"
  
  navbar:
    left:
      - href: index.qmd
        text: صفحه اصلی
      - text: فصل‌ها
        menu:
          - text: "فصل ۱: مقدمه و مفاهیم پایه توزیع نرمال"
            href: chapter1/index.qmd
          - text: "فصل ۲: گراف‌های بیزی - ساختار، استقلال و ارزیابی" 
            href: chapter2/index.qmd
          - text: "فصل ۳: موضوعات پیشرفته"
            href: chapter3/index.qmd
          - text: "فصل ۴: پروژه‌ها و کاربردها"
            href: chapter4/index.qmd

  sidebar:
    style: "floating"
    contents:
      - text: "صفحه اصلی"
        href: index.qmd
      - text: "فصل ۱"
        href: chapter1/index.qmd
      - text: "فصل ۲"
        href: chapter2/index.qmd
      - text: "فصل ۳"
        href: chapter3/index.qmd
      - text: "فصل ۴"
        href: chapter4/index.qmd
  
format:
  html:
    theme: cosmo
    css: assets/css/custom.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-tools: false
    code-fold: false
    lang: fa
    dir: rtl
    
execute:
  freeze: auto

